services:
  - type: web
    name: taskflow-backend
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate --config prisma7.config.ts && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: BCRYPT_SALT_ROUNDS
        value: 10
      - key: BACKEND_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SUPER_ADMIN_NAME
        value: Super Admin
      - key: SUPER_ADMIN_EMAIL
        sync: false
      - key: SUPER_ADMIN_PASSWORD
        sync: false
      - key: REDIS_USER
        value: default
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: EMAIL_SENDER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: BKASH_BASE_URL
        value: https://tokenized.sandbox.bka.sh/v1.2.0-beta
      - key: BKASH_USERNAME
        sync: false
      - key: BKASH_PASSWORD
        sync: false
      - key: BKASH_APP_KEY
        sync: false
      - key: BKASH_APP_SECRET
        sync: false
      - key: BKASH_CALLBACK_URL
        sync: false
